[package]
name = "idalib-sys"
authors = ["Sam L. Thomas <sam@binarly.io>", "Yegor Vasilenko <yegor@binarly.io>"]
version = "0.1.1+9.0.240930"
description = "Idiomatic bindings to IDA SDK"
repository = "https://github.com/binarly-io/idalib"
documentation = "https://binarly-io.github.io/idalib/idalib_sys"
license = "MIT OR Apache-2.0"
readme = "../README.md"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1"
autocxx = "0.27"
bitflags = "2"
cxx = "1"
thiserror = "1"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.52.0", features = ["Win32_System_Threading"] }

[build-dependencies]
autocxx-bindgen = "0.69"
autocxx-build = "0.27"
cxx-build = "1"
