[package]
name = "idalib"
authors = ["Sam L. Thomas <sam@binarly.io>", "Yegor Vasilenko <yegor@binarly.io>"]
version = "0.4.1+9.0.241217"
description = "Idiomatic bindings to IDA SDK"
repository = "https://github.com/binarly-io/idalib"
documentation = "https://binarly-io.github.io/idalib/idalib"
license = "MIT OR Apache-2.0"
readme = "../README.md"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1"
autocxx = "0.28"
bitflags = "2"
cxx = "1"
idalib-sys = { version = "0.4", path = "../idalib-sys" }
thiserror = "1"

[build-dependencies]
idalib-build = { version = "0.4", path = "../idalib-build" }
