name: build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: prepare IDA SDK
        env:
          IDASDK90_URL: ${{ secrets.IDASDK90_URL }}
          IDASDK90_PASSWORD: ${{ secrets.IDASDK90_PASSWORD }}
        run: |
          curl -o "${{ runner.temp }}/idasdk90.zip" -L "$IDASDK90_URL"
          unzip -d "${{ runner.temp }}" -P "$IDASDK90_PASSWORD" "${{ runner.temp }}/idasdk90.zip"
      - name: build
        env:
          IDASDKDIR: "${{ runner.temp }}/idasdk90"
        run: cargo build
